[tox]
envlist =
;    py310
;    py311
;    py312
;    py313
;    py314
    py315

requires =
    tox-uv>=1.28

[testenv:py312]
basepython = python3.12.10
commands = pytest

[testenv:py315]
basepython = python3.15
extras =
    gitlab
    antitamper
    selfcheck
    js-miniracer
    js-dukpy
    ; lua ; no binaries
    ; fast ; rtoml not yet

[testenv]
extras =
    all
deps =
    # parameterized
    pytest>=7.4.4
    pytest-cov>=4.1.0
    toml;python_version<'3.11'
    pytest-benchmark>=4.0.0
    hypothesis>=6.96.0
    pytest-xdist>=3.5.0
commands =
    pytest test -q -n 5  --dist=loadfile --cov=tuochat --cov-fail-under=35 -p no:benchmark
    python scripts/run_benchmarks.py test_perf/test_perf.py test_perf/test_perf_fast.py --benchmark-min-rounds=5 --benchmark-min-time=0.1 -p no:xdist
    ;pytest test -vv no:xdist --benchmark-only
setenv =
    PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
