"""Help section data for tuochat — changes when new commands are added."""

from __future__ import annotations

HELP_SECTIONS = [
    (
        "session",
        "Session and Setup",
        [
            "  /help               Show this help",
            "  /help menu          Show the menu-style accessible help view",
            "  /help-menu          Show the menu-style accessible help view",
            "  /status             Show current conversation status",
            "  /config [json]      Show active configuration (Markdown by default)",
            "  /doctor             Run diagnostics and connectivity checks",
            "  /about              Show version, author, and license",
            "  /setup              Re-run interactive configuration setup",
            "  /shortcuts          Show keyboard shortcuts for the current input backend",
            "  /model [duo|eliza]  Select the active model for this session",
            "  /duo-model          Probe or set the server-side Duo model when GitLab supports it",
            "  /tutorial [lesson|pick]  Run the tutorial or jump to a lesson",
        ],
    ),
    (
        "files",
        "Attachments and Context",
        [
            "  /files              List include-able files",
            "  /approve-checks     Strip .check from safe draft files in the current workspace",
            "  /diff               Show diffs for adjacent .check files and list unpaired drafts",
            "  /include, /attach [path|n]  Include a file by path or numbered selection",
            "  /include-last       Re-include the last file only if it changed",
            "  /map [glob] [limit] Build a recursive file map and optionally attach it",
            "  /code-map [glob] [limit] Attach matching text files as one fenced code bundle",
            "  /detach [path|n|all] Remove pending attachment(s) before sending",
            "  /web <URL>          Fetch a web page and attach it as markdown to the next request",
            "  /web-preview <URL>  Preview a web page fetch then confirm before attaching",
            "  /skills             List discovered skills by source",
            "  /skill [path|n]     Load a skill file into the current conversation",
            "  /template [path|n]  Run a prompt template and fill its variables",
            "  /custom             Pick custom instructions for the next new conversation",
            "  /context            Show current chat context summary",
            "  /token-check        Estimate current prompt/context size",
            "  /timeout [seconds]  Show or temporarily override timeout for this session",
            "  /verbose [on|off]   Toggle context-used/remaining output",
        ],
    ),
    (
        "history",
        "Conversation History",
        [
            "  /new                Start a fresh conversation",
            "  /clear              Clear the current chat and start a fresh conversation",
            "  /classify [marking] Set document classification for this conversation",
            "  /usage              Show weekly token and cost usage (resets Sunday)",
            "  /update-bagit       Refresh archive-change hashes and metadata for saved archives",
            "  /check-bagit        Check whether saved archives changed since the last BagIt update",
            "  /title [new title]  Show or set the conversation title",
            "  /archive            Archive the current conversation (exclude from resume list)",
            "  /unarchive [n|all]  Restore archived conversations",
            "  /resume [id|n]      Resume a saved conversation by id or numbered selection",
            "  /delete [id|n]      Delete a saved conversation from sqlite storage",
            "  /search [query]     Search saved conversations and optionally resume one",
            "  /open               Open the conversation archive folder on disk",
            "  /log, /history      Show the local slash-command and turn log",
        ],
    ),
    (
        "output",
        "Output and Safety",
        [
            "  /stream on|off      Toggle streaming for this session",
            "  /mask on|off        Toggle on-screen sensitive-data masking, including known PATs",
            "  /dot-timer on|off   Print one dot per second until output starts",
            "  /blind on|off       Toggle blind-friendly output for this session",
            "  /no-write on|off    Toggle local persistence",
            "  /write-here-mode on|off  Write named generated files into the cwd and keep transcripts in .tuochat",
            "  /approve-writes on|off  Ask before cwd writes made by /write-here-mode",
            "  /no-code-mode on|off  Hide shell-like fenced code on screen",
            "  /retry              Re-send the last user message",
            "  /copy               Copy the latest assistant response to the clipboard",
        ],
    ),
    (
        "exit",
        "Exit and Cleanup",
        [
            "  /nuke               Delete centralized app data after double confirmation",
            "  /exit, /quit        Exit the REPL",
            "  /done               End-of-day exit (alias for /quit)",
        ],
    ),
]

HELP_SECTION_LOOKUP = {key: (title, lines) for key, title, lines in HELP_SECTIONS}

HELP_TOPIC_ALIASES: dict[str, str] = {
    "session": "session",
    "setup": "session",
    "general": "session",
    "menu": "menu",
    "help-menu": "menu",
    "helpmenu": "menu",
    "files": "files",
    "file": "files",
    "approve-checks": "files",
    "diff": "files",
    "attachments": "files",
    "attachment": "files",
    "context": "files",
    "map": "files",
    "code-map": "files",
    "codemap": "files",
    "history": "history",
    "conversation": "history",
    "archive": "history",
    "resume": "history",
    "output": "output",
    "safety": "output",
    "mask": "output",
    "stream": "output",
    "blind": "output",
    "no-write": "output",
    "nocode": "output",
    "exit": "exit",
    "quit": "exit",
    "cleanup": "exit",
}
