"""Generate the embedded package hash manifest for tamper verification."""

from __future__ import annotations

import base64
import hashlib
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
PACKAGE_DIR = ROOT_DIR / "tuochat"
OUTPUT_PATH = PACKAGE_DIR / "security" / "tamper_manifest.py"
SKIP_RELATIVE_PATH = "security/tamper_manifest.py"


def urlsafe_b64_nopad(data: bytes) -> str:
    """Return URL-safe base64 without trailing padding."""
    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def sha256_file(path: Path) -> str:
    """Hash a file with sha256 and return the RECORD-style digest."""
    hash_value = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            hash_value.update(chunk)
    return urlsafe_b64_nopad(hash_value.digest())


def build_manifest() -> dict[str, str]:
    """Build a package-relative manifest for Python source files."""
    manifest: dict[str, str] = {}
    for file_path in sorted(PACKAGE_DIR.rglob("*.py")):
        relative_path = file_path.relative_to(PACKAGE_DIR).as_posix()
        if relative_path == SKIP_RELATIVE_PATH:
            continue
        manifest[relative_path] = sha256_file(file_path)
    return manifest


def render_manifest_module(manifest: dict[str, str]) -> str:
    """Render the generated Python module content."""
    lines = [
        '"""Generated fallback manifest for package tamper checks."""',
        "",
        "# Generated by scripts/gen_tamper_manifest.py",
        "MANIFEST = {",
    ]
    for relative_path, digest in manifest.items():
        lines.append(f"    {relative_path!r}: {digest!r},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    """Write the generated manifest module into the security package."""
    OUTPUT_PATH.write_text(render_manifest_module(build_manifest()), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
